[loggers]
keys=root,uvicorn,apscheduler

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=standard

[logger_root]
level=INFO
handlers=consoleHandler,fileHandler

[logger_uvicorn]
level=INFO
handlers=consoleHandler,fileHandler
qualname=uvicorn
propagate=0

[logger_apscheduler]
level=INFO
handlers=consoleHandler,fileHandler
qualname=apscheduler
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=INFO
formatter=standard
args=(sys.stdout,)

[handler_fileHandler]
class=handlers.RotatingFileHandler
level=INFO
formatter=standard
args=('logs/app.log', 'a', 10485760, 5)

[formatter_standard]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=%Y-%m-%d %H:%M:%S
